# Generated by Django 5.2.4 on 2025-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cierrediario_egreso_ingresovirtual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=100),
        ),
    ]
