# Generated by Django 5.2.5 on 2025-10-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
