# Generated by Django 5.2.7 on 2025-10-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_gasto'),
        ('tasks', '0007_remove_producto_stock'),
    ]

    operations = [
    ]
