# Generated by Django 5.2.5 on 2025-11-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_0007_gasto_0007_remove_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoefectivo',
            name='cantidad_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresoefectivo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.producto'),
        ),
        migrations.AddField(
            model_name='ingresovirtual',
            name='cantidad_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresovirtual',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.producto'),
        ),
        migrations.AlterField(
            model_name='ingresovirtual',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
